### PR TITLE
write code to airtable only when in production environment

### PR DESCRIPTION
**Pull request by igor-kamil**
avoid writing generated code into airtable when in development environment
consider disable writing generated code into airtable in the future and use only https://kod.sng.sk/print instead

### CODE REVIEW

**Comment by rastislav-chynoransky** [comment]
> consider disable writing generated code into airtable in the future

Can't we do it now?

**Review by rastislav-chynoransky — CHANGES_REQUESTED** [review]
> consider disable writing generated code into airtable in the future

Can't we do it now?

**Comment by eronisko** [comment]
It might be useful to create a development Airtable instance

**Comment by igor-kamil** [comment]
@rastislav-chynoransky your question is right. that was the original idea. I removed it completely when importing localy. 
However AFAIK this really helped in testing phase (@ustengrav and maybe others?). There was a reason to add it... to debug each code before release. Also to quickly check the artwork anytime.
I am up for making it "obsolete" and "ready to remove" once it's proofed it's not needed anymore. For now I will prefer to keep it as I proposed.

**Review by rastislav-chynoransky — APPROVED** [review]

**Pull request merged**
